### ISSUE TITLE
Check QAI on start up

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/MiCall#473]
`micall_watcher.py` currently checks Kive for an external directory when it starts up, and complains if it doesn't find one or if it can't connect to Kive. It would also be useful to check that it can connect to QAI and that the MiCall pipeline it's expecting has been configured. If not, it should log an error and proceed with sending jobs to Kive.

When QAI isn't configured properly, it seems to complain about twice an hour after the first run finishes processing. Try to include the retry logic with increasing delays for when to try uploading to QAI. This might be related to the changes for #471, so you have three independent processes:

1. Starting new Kive jobs.
2. Uploading completed runs to QAI, with retry delay logic.
3. Checking the status of active Kive jobs.

**Comment by dmacmillan** [comment]
I've pushed some changes to [my branch](https://github.com/cfe-lab/MiCall/tree/run_for_dan) to address this issue. I've tested that my new function behaves correctly when QAI is available or not.

I might have the logic in the wrong place because it looks like the QAI check will only run once here. I'll clarify and then see about adding in retry logic.
